TASK_TYPE_TRAIN = 'train'
TASK_TYPE_PREDICT = 'predict'
TASK_TYPE_USER_EMBEDDING = 'user_embedding'
TASK_TYPE_ITEM_EMBEDDING = 'item_embedding'

CONFIG_FEATURE_NAME = 'name'
CONFIG_FEATURE_TYPE = 'type'
CONFIG_FEATURE_LAYERS = 'layers'

CONFIG_FEATURE_LAYERS_BUILD_IN_HASH = '__hash__'
CONFIG_FEATURE_LAYERS_BUILD_IN_READUCE_MEAN = '__mean__'
CONFIG_FEATURE_LAYERS_BUILD_IN_READUCE_SUM = '__sum__'

CONFIG_FEATURE_EXTRA_COLUMNS = 'extra_columns'
CONFIG_FEATURE_TYPE_SINGLE = 'single'
CONFIG_FEATURE_TYPE_SEQ = 'seq'
