TASK_TYPE_TRAIN = 'train'
TASK_TYPE_PREDICT = 'predict'
TASK_TYPE_USER_EMBEDDING = 'user_embedding'
TASK_TYPE_ITEM_EMBEDDING = 'item_embedding'

CONFIG_COLUMNS = 'columns'
CONFIG_COLUMNS_NAME = 'name'
CONFIG_COLUMNS_TYPE = 'type'

CONFIG_FEATURE_NAME = 'name'
CONFIG_FEATURE_LAYERS = 'layers'

CONFIG_COLUMNS_TYPE_SINGLE = 'single'
CONFIG_COLUMNS_TYPE_SEQ = 'seq'

CONFIG_LOSS = 'loss'
CONFIG_LOSS_NAME = 'name'

NUM_PARALLEL_CALLS = 96
